In [1]:
import numpy as np

#### 标量

In [2]:
scalar=5
scalar

5

#### 向量

In [3]:
vector=np.array([1,2])
vector

array([1, 2])

#### 矩阵

In [4]:
matrix = np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

#### 张量

In [5]:
tensor=np.array([
     [[1,2,3],[4,5,6],[7,8,9]],
     [[11,12,13],[14,15,16],[17,18,19]],
     [[21,22,13],[24,25,26],[27,28,29]],
])
tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 13],
        [24, 25, 26],
        [27, 28, 29]]])

#### 矩阵转置

In [6]:
A = np.array([[1.,2.],[1.,0.],[2.,3.]])
A_t = A.transpose()
print(A)
print(A_t)

[[1. 2.]
 [1. 0.]
 [2. 3.]]
[[1. 1. 2.]
 [2. 0. 3.]]


#### 矩阵加法

In [8]:
a=np.array([[1.,2.],[3.,4.]])
b=np.array([[6.,7.],[8.,9.]])
print(a+b)

[[ 7.  9.]
 [11. 13.]]


#### 矩阵乘法

In [10]:
m1 = np.array([[1.,3.],[1.,0.]])
m2 = np.array([[1.,2.],[5.,0.]])
print(np.dot(m1,m2))
print(np.multiply(m1,m2))
print(m1*m2)

[[16.  2.]
 [ 1.  2.]]
[[1. 6.]
 [5. 0.]]
[[1. 6.]
 [5. 0.]]


In [11]:
v1 = np.array([1.,2.])
v2 = np.array([4.,5.])
np.dot(v1,v2)

14.0

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
A=[[1.,2.],[3.,4.]]
A_inv = np.linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [16]:
a = np.array([1.,3.])
print(np.linalg.norm(a,ord=2))
print(np.linalg.norm(a,ord=1))
print(np.linalg.norm(a,ord=np.inf))

3.1622776601683795
4.0
3.0


In [18]:
a = np.array([[1.,3.],[2.,1.]])
print(np.linalg.norm(a,ord="fro"))

3.872983346207417
