In [1]:
import numpy as np

#### 标量

In [2]:
scalar=5
scalar

5

#### 向量

In [3]:
vector=np.array([1,2])
vector

array([1, 2])

#### 矩阵

In [4]:
matrix = np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

#### 张量

In [5]:
tensor=np.array([
     [[1,2,3],[4,5,6],[7,8,9]],
     [[11,12,13],[14,15,16],[17,18,19]],
     [[21,22,13],[24,25,26],[27,28,29]],
])
tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 13],
        [24, 25, 26],
        [27, 28, 29]]])

#### 矩阵转置

In [6]:
A = np.array()

SyntaxError: invalid syntax (<ipython-input-6-a6def14c837f>, line 1)

In [ ]:
let matrix = Matrix{val:vec![vec![1,2],vec![3,4]]};
let matrix_t=matrix.transpose();
matrix_t

#### 矩阵加法

In [ ]:
use std::ops::{Add,Sub,};
impl Add for Matrix{
    type Output = Self;
    fn add(self, other: Self) -> Self {
        self.val[]
        Self {val: self.x + other.x, y: self.y + other.y}
    }
}

In [ ]:
let a = vec![vec![1.,2.],vec![3.,4.]];
let b = vec![vec![6.,7.],vec![8.,9.]];